# WARNING - Generated by {fusen} from dev/flat_minimal.Rmd: do not edit by hand

#' replace_lookup_table Title
#'
#' @param mp_service_account_name The Mixpanel Service Account Name
#' @param mp_service_account_secret The Mixpanel Service Account Token
#' @param mp_project_id The Mixpanel Project ID
#' @param lookup_table_id The id to identify the lookup table
#' @param table_to_replace The dataframe to replace the lookup table
#' 
#' @return 
#' Success Message if Lookup table has been replaced successfully
#' @export

# test_lookup <- tibble::tibble(`$distinct_id` = c(1051, 6140),
#                               IS_SUCCESSFUL_SUPPLIER = c(TRUE, FALSE),
#                               N_DEALS = c(4, 0))
# 

replace_lookup_table <- function(mp_service_account_name = Sys.getenv("MP_SERVICE_ACCOUNT_NAME"),
                              mp_service_account_secret = Sys.getenv("MP_SERVICE_ACCOUNT_TOKEN"),
                              mp_project_id = Sys.getenv("MP_PROJECT_ID"),
                              lookup_table_id,
                              table_to_replace) {
    
    table_to_replace_csv <- readr::format_csv(table_to_replace, escape = "none")
    
    resp <- httr2::request("https://api.mixpanel.com/lookup-tables") |> 
        httr2::req_auth_basic(username = mp_service_account_name,
                     password = mp_service_account_secret) |> 
        httr2::req_headers(accept = "application/json",
                           `content-type` = "text/csv") |> 
        httr2::req_url_path_append(lookup_table_id) |> 
        httr2::req_url_query(project_id = mp_project_id) |> 
        httr2::req_body_raw(table_to_replace_csv) |> 
        httr2::req_method("PUT") |> 
        httr2::req_perform()
    
    return(resp)
}

